# GET USERS
GET http://localhost:9000/api/v1/users/

###

# GET USER
GET http://localhost:9000/api/v1/users/id

###

# CREATE USER
POST http://localhost:9000/api/v1/users/
Content-Type: application/json

{
  "name": "Aryan",
  "artists": [
    {
      "name": "Juice World",
      "image": {
        "height": 160,
        "width": 160,
        "url": "juiceworld.jpg"
      },
      "url": "juiceworld.com",
      "popularity": 80,
      "artistId": "juiceworld id"
    },
    {
      "name": "Juice World 2",
      "image": {
        "height": 160,
        "width": 160,
        "url": "juiceworld2.jpg"
      },
      "url": "juiceworld2.com",
      "popularity": 100,
      "artistId": "juiceworld id2"
    }
  ],
  "tracks": [
    {
      "name": "Hate the other side",
      "image": "song.jpg",
      "url": "song.com",
      "album": "ALBUM",
      "trackId": "song's track id"
    }
  ],
  "features": [
    {
      "energy": 10,
      "valence": 20,
      "dancebility": 30,
      "liveness": 40
    }
  ]
}

###

# UPDATE USER
PATCH http://localhost:9000/api/v1/users/604d15555c2d92afb5bdadf0
Content-Type: application/json

{
  "name": "Aryan New"
}

###

# DELETE USER
DELETE http://localhost:9000/api/v1/users/604d15555c2d92afb5bdadf0